//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"

	"github.com/ai-sdlc-framework/ai-sdlc/sdk-go/core"
)

// ── Pipeline ────────────────────────────────────────────────────────

func (in *PipelineResource) DeepCopyInto(out *PipelineResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = deepCopyPipelineSpec(in.Spec)
	if in.Status != nil {
		out.Status = deepCopyPipelineStatus(in.Status)
	}
}

func (in *PipelineResource) DeepCopy() *PipelineResource {
	if in == nil {
		return nil
	}
	out := new(PipelineResource)
	in.DeepCopyInto(out)
	return out
}

func (in *PipelineResource) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *PipelineResourceList) DeepCopyInto(out *PipelineResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]PipelineResource, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *PipelineResourceList) DeepCopy() *PipelineResourceList {
	if in == nil {
		return nil
	}
	out := new(PipelineResourceList)
	in.DeepCopyInto(out)
	return out
}

func (in *PipelineResourceList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// ── AgentRole ───────────────────────────────────────────────────────

func (in *AgentRoleResource) DeepCopyInto(out *AgentRoleResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = deepCopyAgentRoleSpec(in.Spec)
	if in.Status != nil {
		out.Status = deepCopyAgentRoleStatus(in.Status)
	}
}

func (in *AgentRoleResource) DeepCopy() *AgentRoleResource {
	if in == nil {
		return nil
	}
	out := new(AgentRoleResource)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentRoleResource) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *AgentRoleResourceList) DeepCopyInto(out *AgentRoleResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AgentRoleResource, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *AgentRoleResourceList) DeepCopy() *AgentRoleResourceList {
	if in == nil {
		return nil
	}
	out := new(AgentRoleResourceList)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentRoleResourceList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// ── QualityGate ─────────────────────────────────────────────────────

func (in *QualityGateResource) DeepCopyInto(out *QualityGateResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = deepCopyQualityGateSpec(in.Spec)
	if in.Status != nil {
		out.Status = deepCopyQualityGateStatus(in.Status)
	}
}

func (in *QualityGateResource) DeepCopy() *QualityGateResource {
	if in == nil {
		return nil
	}
	out := new(QualityGateResource)
	in.DeepCopyInto(out)
	return out
}

func (in *QualityGateResource) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *QualityGateResourceList) DeepCopyInto(out *QualityGateResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]QualityGateResource, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *QualityGateResourceList) DeepCopy() *QualityGateResourceList {
	if in == nil {
		return nil
	}
	out := new(QualityGateResourceList)
	in.DeepCopyInto(out)
	return out
}

func (in *QualityGateResourceList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// ── AutonomyPolicy ──────────────────────────────────────────────────

func (in *AutonomyPolicyResource) DeepCopyInto(out *AutonomyPolicyResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = deepCopyAutonomyPolicySpec(in.Spec)
	if in.Status != nil {
		out.Status = deepCopyAutonomyPolicyStatus(in.Status)
	}
}

func (in *AutonomyPolicyResource) DeepCopy() *AutonomyPolicyResource {
	if in == nil {
		return nil
	}
	out := new(AutonomyPolicyResource)
	in.DeepCopyInto(out)
	return out
}

func (in *AutonomyPolicyResource) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *AutonomyPolicyResourceList) DeepCopyInto(out *AutonomyPolicyResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AutonomyPolicyResource, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *AutonomyPolicyResourceList) DeepCopy() *AutonomyPolicyResourceList {
	if in == nil {
		return nil
	}
	out := new(AutonomyPolicyResourceList)
	in.DeepCopyInto(out)
	return out
}

func (in *AutonomyPolicyResourceList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// ── AdapterBinding ──────────────────────────────────────────────────

func (in *AdapterBindingResource) DeepCopyInto(out *AdapterBindingResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = deepCopyAdapterBindingSpec(in.Spec)
	if in.Status != nil {
		out.Status = deepCopyAdapterBindingStatus(in.Status)
	}
}

func (in *AdapterBindingResource) DeepCopy() *AdapterBindingResource {
	if in == nil {
		return nil
	}
	out := new(AdapterBindingResource)
	in.DeepCopyInto(out)
	return out
}

func (in *AdapterBindingResource) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *AdapterBindingResourceList) DeepCopyInto(out *AdapterBindingResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AdapterBindingResource, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *AdapterBindingResourceList) DeepCopy() *AdapterBindingResourceList {
	if in == nil {
		return nil
	}
	out := new(AdapterBindingResourceList)
	in.DeepCopyInto(out)
	return out
}

func (in *AdapterBindingResourceList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// ── Deep copy helpers for core spec types ───────────────────────────
// These copy types that contain slices, maps, or pointers.

func deepCopyPipelineSpec(in core.PipelineSpec) core.PipelineSpec {
	out := in
	if in.Triggers != nil {
		out.Triggers = make([]core.Trigger, len(in.Triggers))
		copy(out.Triggers, in.Triggers)
	}
	if in.Providers != nil {
		out.Providers = make(map[string]core.Provider, len(in.Providers))
		for k, v := range in.Providers {
			out.Providers[k] = v
		}
	}
	if in.Stages != nil {
		out.Stages = make([]core.Stage, len(in.Stages))
		copy(out.Stages, in.Stages)
	}
	return out
}

func deepCopyPipelineStatus(in *core.PipelineStatus) *core.PipelineStatus {
	if in == nil {
		return nil
	}
	out := *in
	if in.Conditions != nil {
		out.Conditions = make([]core.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
	if in.StageAttempts != nil {
		out.StageAttempts = make(map[string]int, len(in.StageAttempts))
		for k, v := range in.StageAttempts {
			out.StageAttempts[k] = v
		}
	}
	return &out
}

func deepCopyAgentRoleSpec(in core.AgentRoleSpec) core.AgentRoleSpec {
	out := in
	if in.Tools != nil {
		out.Tools = make([]string, len(in.Tools))
		copy(out.Tools, in.Tools)
	}
	if in.Handoffs != nil {
		out.Handoffs = make([]core.Handoff, len(in.Handoffs))
		copy(out.Handoffs, in.Handoffs)
	}
	if in.Skills != nil {
		out.Skills = make([]core.Skill, len(in.Skills))
		copy(out.Skills, in.Skills)
	}
	return out
}

func deepCopyAgentRoleStatus(in *core.AgentRoleStatus) *core.AgentRoleStatus {
	if in == nil {
		return nil
	}
	out := *in
	return &out
}

func deepCopyQualityGateSpec(in core.QualityGateSpec) core.QualityGateSpec {
	out := in
	if in.Gates != nil {
		out.Gates = make([]core.Gate, len(in.Gates))
		copy(out.Gates, in.Gates)
	}
	return out
}

func deepCopyQualityGateStatus(in *core.QualityGateStatus) *core.QualityGateStatus {
	if in == nil {
		return nil
	}
	out := *in
	if in.Conditions != nil {
		out.Conditions = make([]core.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
	return &out
}

func deepCopyAutonomyPolicySpec(in core.AutonomyPolicySpec) core.AutonomyPolicySpec {
	out := in
	if in.Levels != nil {
		out.Levels = make([]core.AutonomyLevel, len(in.Levels))
		copy(out.Levels, in.Levels)
	}
	if in.PromotionCriteria != nil {
		out.PromotionCriteria = make(map[string]core.PromotionCriteria, len(in.PromotionCriteria))
		for k, v := range in.PromotionCriteria {
			out.PromotionCriteria[k] = v
		}
	}
	if in.DemotionTriggers != nil {
		out.DemotionTriggers = make([]core.DemotionTrigger, len(in.DemotionTriggers))
		copy(out.DemotionTriggers, in.DemotionTriggers)
	}
	return out
}

func deepCopyAutonomyPolicyStatus(in *core.AutonomyPolicyStatus) *core.AutonomyPolicyStatus {
	if in == nil {
		return nil
	}
	out := *in
	if in.Agents != nil {
		out.Agents = make([]core.AgentAutonomyStatus, len(in.Agents))
		copy(out.Agents, in.Agents)
	}
	return &out
}

func deepCopyAdapterBindingSpec(in core.AdapterBindingSpec) core.AdapterBindingSpec {
	out := in
	if in.Config != nil {
		out.Config = make(map[string]interface{}, len(in.Config))
		for k, v := range in.Config {
			out.Config[k] = v
		}
	}
	return out
}

func deepCopyAdapterBindingStatus(in *core.AdapterBindingStatus) *core.AdapterBindingStatus {
	if in == nil {
		return nil
	}
	out := *in
	return &out
}
