/**
 * Proposal generator — creates draft automation artifacts from detected patterns.
 * Each pattern type maps to a specific artifact: command, skill, hook, or workflow.
 */

import type { DetectedPattern, CanonicalStep } from './types.js';
import type { PatternProposal } from '../state/types.js';

/**
 * Generate an automation proposal from a detected pattern.
 */
export function generateProposal(pattern: DetectedPattern): Omit<PatternProposal, 'patternId'> {
  const name = generateName(pattern);

  switch (pattern.suggestedArtifactType) {
    case 'command':
      return {
        proposalType: pattern.patternType,
        artifactType: 'command',
        artifactPath: `.claude/commands/${name}.md`,
        draftContent: generateCommandTemplate(name, pattern),
        confidence: computeProposalConfidence(pattern),
        status: 'pending',
      };
    case 'skill':
      return {
        proposalType: pattern.patternType,
        artifactType: 'skill',
        artifactPath: `.claude/skills/${name}/SKILL.md`,
        draftContent: generateSkillTemplate(name, pattern),
        confidence: computeProposalConfidence(pattern),
        status: 'pending',
      };
    case 'workflow':
      return {
        proposalType: pattern.patternType,
        artifactType: 'workflow',
        artifactPath: `.github/workflows/auto-${name}.yml`,
        draftContent: generateWorkflowTemplate(name, pattern),
        confidence: computeProposalConfidence(pattern),
        status: 'pending',
      };
    case 'hook':
      return {
        proposalType: pattern.patternType,
        artifactType: 'hook',
        artifactPath: `.claude/hooks/${name}.sh`,
        draftContent: generateHookTemplate(name, pattern),
        confidence: computeProposalConfidence(pattern),
        status: 'pending',
      };
    default:
      return {
        proposalType: pattern.patternType,
        artifactType: 'command',
        artifactPath: `.claude/commands/${name}.md`,
        draftContent: generateCommandTemplate(name, pattern),
        confidence: computeProposalConfidence(pattern),
        status: 'pending',
      };
  }
}

/**
 * Generate a kebab-case name from the pattern's steps.
 */
export function generateName(pattern: DetectedPattern): string {
  // Take the most distinctive tool+action pairs
  const parts: string[] = [];

  for (const step of pattern.steps) {
    const action = step.action
      .replace(/[^a-zA-Z0-9\s]/g, '')
      .trim()
      .split(/\s+/)
      .slice(0, 2)
      .join('-')
      .toLowerCase();

    if (action && !parts.includes(action)) {
      parts.push(action);
    }
    if (parts.length >= 3) break;
  }

  const name =
    parts.length > 0 ? `auto-${parts.join('-')}` : `auto-pattern-${pattern.hash.slice(0, 8)}`;
  return name.slice(0, 50);
}

function stepsToMarkdown(steps: CanonicalStep[]): string {
  return steps
    .map((s, i) => {
      const desc = s.action.includes(':') ? `${s.tool}: ${s.action}` : `Run \`${s.action}\``;
      return `${i + 1}. ${desc}`;
    })
    .join('\n');
}

function generateCommandTemplate(name: string, pattern: DetectedPattern): string {
  return `---
name: ${name}
description: Auto-generated from detected workflow pattern (${pattern.patternType})
argument-hint: [optional-args]
---

# ${name}

> Auto-generated from pattern detection. Confidence: ${(pattern.confidence * 100).toFixed(0)}%
> Observed ${pattern.frequency} times across ${pattern.sessionCount} sessions.

## Steps

${stepsToMarkdown(pattern.steps)}

## Notes

This command was auto-generated by the workflow pattern detection engine.
Review and customize before using in production.
`;
}

function generateSkillTemplate(name: string, pattern: DetectedPattern): string {
  return `---
name: ${name}
description: Auto-generated skill from detected ${pattern.patternType} pattern
---

# ${name}

> Auto-generated from pattern detection. Confidence: ${(pattern.confidence * 100).toFixed(0)}%
> Observed ${pattern.frequency} times across ${pattern.sessionCount} sessions.

## Workflow

${stepsToMarkdown(pattern.steps)}

## Customization

This skill was auto-generated. Modify the steps above to match your
specific use case.
`;
}

function generateWorkflowTemplate(name: string, pattern: DetectedPattern): string {
  const schedule = '0 9 * * 1'; // Default: Monday 9am
  return `# Auto-generated workflow from pattern detection
# Pattern: ${pattern.patternType}
# Confidence: ${(pattern.confidence * 100).toFixed(0)}%
# Observed ${pattern.frequency} times across ${pattern.sessionCount} sessions

name: Auto ${name}

on:
  schedule:
    - cron: '${schedule}'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
${pattern.steps.map((s) => `      - name: ${s.tool} ${s.action}\n        run: echo "TODO: implement ${s.action}"`).join('\n')}
`;
}

function generateHookTemplate(name: string, pattern: DetectedPattern): string {
  return `#!/bin/bash
# Auto-generated hook from pattern detection
# Pattern: ${pattern.patternType}
# Confidence: ${(pattern.confidence * 100).toFixed(0)}%

set -euo pipefail

# TODO: Implement hook logic for pattern:
${pattern.steps.map((s) => `# - ${s.tool}: ${s.action}`).join('\n')}

exit 0
`;
}

function computeProposalConfidence(pattern: DetectedPattern): number {
  // Base confidence from pattern detection
  let confidence = pattern.confidence;

  // Template fit: commands and skills have better template mapping
  if (pattern.suggestedArtifactType === 'command' || pattern.suggestedArtifactType === 'skill') {
    confidence *= 1.0; // Perfect fit
  } else if (pattern.suggestedArtifactType === 'workflow') {
    confidence *= 0.8; // Periodic tasks need schedule tuning
  } else {
    confidence *= 0.7; // Hooks need manual implementation
  }

  return Math.min(1.0, confidence);
}
