apiVersion: ai-sdlc.io/v1alpha1
kind: AdapterBinding
metadata:
  name: github-adapter
  labels:
    ai-sdlc.io/component: dogfood
spec:
  interface: IssueTracker
  type: github
  version: 0.1.0
  config:
    org: ai-sdlc-framework
    repo: ai-sdlc
    token:
      secretRef: github-token
